In [2]:
import pandas as pd
import sqlite3

In [3]:
conn = sqlite3.Connection('inventory.db')

In [4]:
tables = pd.read_sql_query("select name from sqlite_master where type ='table'",conn)
tables

                     name
0         begin_inventory
1           end_inventory
2               purchases
3         purchase_prices
4                   sales
5          vendor_invoice
6    vendor_final_summary
7  vendor_scorecard_final

In [5]:
results = []

for table in tables['name']:
    result = pd.read_sql(f"SELECT COUNT(*) as row_count FROM {table};", conn)
    results.append({
        "table_name": table,
        "row_count": result['row_count'][0]
    })

summary_df = pd.DataFrame(results)
summary_df

               table_name  row_count
0         begin_inventory     206529
1           end_inventory     224489
2               purchases    2372474
3         purchase_prices      12261
4                   sales   12825363
5          vendor_invoice       5543
6    vendor_final_summary        129
7  vendor_scorecard_final        129

* uncheckd pandas display limit

In [6]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [7]:
for table in tables['name']:
    print(f"\nTable: {table}")
    df = pd.read_sql(f"SELECT * FROM {table} LIMIT 5;", conn)
    display(df)

Table: begin_inventory

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

Table: end_inventory

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

Table: purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

Table: purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

Table: sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

Table: vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

Table: vendor_final_summary

,VendorNumber,VendorName,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,total_Quantity,total_spend,unit_cost_incl_freight,avg_payment_days,margin_percent,risk_score,risk_band,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,90026,SILVER MOUNTAIN CIDERS,4.5400,11.3900,730.00,17,77.18,52.0,381.48,7.3362,5.17,0.36,17,77.54,4.5612,30.50,0.00,0.987,HIGH,304.30,79.768271,3.058824,4.942731
1,90033,FANTASY FINE WINES CORP,5.3600,7.9900,750.00,24,128.64,41.0,327.59,7.9900,4.51,0.61,24,129.25,5.3854,29.00,32.92,0.974,HIGH,198.95,60.731402,1.708333,2.546564
2,2396,BLACK PRINCE DISTILLERY INC,7.4547,7.3900,1275.00,807,5971.94,1115.0,11818.85,10.5999,986.13,30.98,807,6002.92,7.4386,33.34,36.15,0.859,HIGH,5846.91,49.471057,1.381660,1.979064
3,90052,HAUNTING WHISPER VYDS,8.0698,11.9900,750.00,669,5388.58,611.0,7325.89,11.9900,67.62,27.61,669,5416.19,8.0959,33.10,32.70,0.854,HIGH,1937.31,26.444705,0.913303,1.359521
4,90017,THE IMPORTED GRAPE LLC,7.2305,18.6775,743.75,2280,16093.77,1736.0,22179.74,12.7763,194.00,80.03,2280,16173.80,7.0938,34.40,43.90,0.836,HIGH,6085.97,27.439321,0.761404,1.378157

Table: vendor_scorecard_final

,VendorNumber,VendorName,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,total_Quantity,total_spend,unit_cost_incl_freight,avg_payment_days,margin_percent,risk_score,risk_band,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,90026,SILVER MOUNTAIN CIDERS,4.5400,11.3900,730.00,17,77.18,52.0,381.48,7.3362,5.17,0.36,17,77.54,4.5612,30.50,0.00,0.987,HIGH,304.30,79.768271,3.058824,4.942731
1,90033,FANTASY FINE WINES CORP,5.3600,7.9900,750.00,24,128.64,41.0,327.59,7.9900,4.51,0.61,24,129.25,5.3854,29.00,32.92,0.974,HIGH,198.95,60.731402,1.708333,2.546564
2,2396,BLACK PRINCE DISTILLERY INC,7.4547,7.3900,1275.00,807,5971.94,1115.0,11818.85,10.5999,986.13,30.98,807,6002.92,7.4386,33.34,36.15,0.859,HIGH,5846.91,49.471057,1.381660,1.979064
3,90052,HAUNTING WHISPER VYDS,8.0698,11.9900,750.00,669,5388.58,611.0,7325.89,11.9900,67.62,27.61,669,5416.19,8.0959,33.10,32.70,0.854,HIGH,1937.31,26.444705,0.913303,1.359521
4,90017,THE IMPORTED GRAPE LLC,7.2305,18.6775,743.75,2280,16093.77,1736.0,22179.74,12.7763,194.00,80.03,2280,16173.80,7.0938,34.40,43.90,0.836,HIGH,6085.97,27.439321,0.761404,1.378157

* Unique Vendor count

In [8]:
query = '''
select count(distinct VendorNumber) as uniqe_vendors
from vendor_invoice
'''
pd.read_sql(query,conn)

   uniqe_vendors
0            126

* uniqe product count

In [9]:
query = """
select count(distinct Brand) as uniqe_brand
from purchases
"""
pd.read_sql(query,conn)

   uniqe_brand
0        10664

* Total Spend per vendor

In [10]:
query = """
select VendorNumber,
VendorName,
sum(Dollars + COALESCE(Freight,0)) as total_spend
from vendor_invoice
group by VendorNumber,VendorName
order by total_spend DESC
"""
vendor_spend = pd.read_sql(query,conn)
vendor_spend.head()

   VendorNumber                   VendorName  total_spend
0          3960  DIAGEO NORTH AMERICA INC     51216828.92
1          4425        MARTIGNETTI COMPANIES  27966193.83
2         12546  JIM BEAM BRANDS COMPANY      24327032.02
3         17035  PERNOD RICARD USA            24247871.78
4           480  BACARDI USA INC              17713664.99

* How much % of the total spend each vendor is taking.

In [11]:
q = """
WITH v AS (
  SELECT VendorNumber, VendorName,
         SUM(Dollars + COALESCE(Freight,0)) AS total_spend
  FROM vendor_invoice
  GROUP BY VendorNumber, VendorName
),
t AS (
  SELECT SUM(total_spend) AS grand_total FROM v
)
SELECT v.VendorNumber, v.VendorName, v.total_spend,
       ROUND(v.total_spend * 100.0 / t.grand_total, 2) AS spend_percentage
FROM v CROSS JOIN t
ORDER BY spend_percentage DESC;
"""
pd.read_sql(q, conn).head(10)

   VendorNumber                   VendorName  total_spend  spend_percentage
0          3960  DIAGEO NORTH AMERICA INC     51216828.92             15.83
1          4425        MARTIGNETTI COMPANIES  27966193.83              8.64
2         12546  JIM BEAM BRANDS COMPANY      24327032.02              7.52
3         17035  PERNOD RICARD USA            24247871.78              7.49
4           480  BACARDI USA INC              17713664.99              5.47
5          1392  CONSTELLATION BRANDS INC     15653446.89              4.84
6          1128  BROWN-FORMAN CORP            13598034.76              4.20
7          9165  ULTRA BEVERAGE COMPANY LLP   13278668.63              4.10
8          3252  E & J GALLO WINERY           12351575.00              3.82
9          9552  M S WALKER INC               10991369.12              3.40

* Total quantity by every vendor

In [12]:
query = """
select
VendorNumber,
VendorName,
sum(Quantity) as  total_Quantity
from vendor_invoice
group by VendorNumber,VendorName
order by total_Quantity	DESC
""" 
pd.read_sql(query,conn).head()

   VendorNumber                   VendorName  total_Quantity
0          3960  DIAGEO NORTH AMERICA INC            5459788
1         12546  JIM BEAM BRANDS COMPANY             2737165
2          4425        MARTIGNETTI COMPANIES         2637275
3          1392  CONSTELLATION BRANDS INC            2325892
4          3252  E & J GALLO WINERY                  1858260

* unit cost by every vendor

In [13]:
q = """
SELECT
  VendorNumber,
  VendorName,
  SUM(Quantity) AS total_Quantity	,
  SUM(Dollars) AS product_dollars,
  SUM(COALESCE(Freight,0)) AS freight_dollars,
  ROUND( (SUM(Dollars) + SUM(COALESCE(Freight,0))) / NULLIF(SUM(Quantity),0), 4) AS unit_cost_incl_freight
FROM vendor_invoice
GROUP BY VendorNumber, VendorName
ORDER BY unit_cost_incl_freight DESC;
"""
pd.read_sql(q, conn).head(10)

,VendorNumber,VendorName,total_Quantity,product_dollars,freight_dollars,unit_cost_incl_freight
0,54,AAPER ALCOHOL & CHEMICAL CO,1,105.07,0.48,105.5500
1,1703,ALISA CARR BEVERAGES,438,34951.68,172.00,80.1911
2,7749,R.P.IMPORTS INC,498,18776.87,91.50,37.8883
3,105,ALTAMAR BRANDS LLC,332,11706.20,62.39,35.4476
4,1273,CALEDONIA SPIRITS INC,8202,259604.70,1319.77,31.8123
5,2561,EDRINGTON AMERICAS,62542,1882832.84,9654.50,30.2595
6,1587,VINEYARD BRANDS LLC,371,10951.51,54.23,29.6651
7,5455,MARSALLE COMPANY,7158,185311.19,937.21,26.0196
8,7239,REMY COINTREAU USA INC,142363,3354958.28,16978.67,23.6855
9,9751,VINEDREA WINES LLC,205,4657.60,24.53,22.8397

* How much time delay to payment by evrey vendor

In [14]:
q = """
SELECT
  VendorNumber,
  VendorName,
  ROUND(AVG(julianday(PayDate) - julianday(InvoiceDate)), 2) AS avg_payment_days,
  MIN(julianday(PayDate) - julianday(InvoiceDate)) AS min_days,
  MAX(julianday(PayDate) - julianday(InvoiceDate)) AS max_days,
  COUNT(*) AS invoices
FROM vendor_invoice
WHERE PayDate IS NOT NULL AND InvoiceDate IS NOT NULL
GROUP BY VendorNumber, VendorName
ORDER BY avg_payment_days DESC;
"""
pd.read_sql(q, conn).head(10)

,VendorNumber,VendorName,avg_payment_days,min_days,max_days,invoices
0,54,AAPER ALCOHOL & CHEMICAL CO,43.00,43.0,43.0,1
1,4901,LAUREATE IMPORTS CO,41.00,41.0,41.0,1
2,6280,UNCORKED,39.71,32.0,45.0,7
3,3551,GILMANTON WINERY & VINEYARD,39.50,31.0,45.0,8
4,9751,VINEDREA WINES LLC,38.80,26.0,48.0,20
5,201359,FLAVOR ESSENCE INC,38.00,38.0,38.0,1
6,4425,MARTIGNETTI COMPANIES,37.89,27.0,48.0,27
7,1703,ALISA CARR BEVERAGES,37.79,27.0,47.0,19
8,287,APPOLO VINEYARDS LLC,37.38,28.0,47.0,13
9,7749,R.P.IMPORTS INC,37.19,31.0,48.0,16

* Standard price vs Actual price 
* which vendor is charging more then the standard price

In [15]:
q = """
SELECT
  p.VendorNumber,
  p.VendorName,
  p.Brand,
  p.Description,
  p.Size,
  ROUND(AVG(p.PurchasePrice), 4) AS avg_actual_price,
  ROUND(AVG(pp.PurchasePrice), 4) AS avg_standard_price,
  ROUND(AVG(p.PurchasePrice - pp.PurchasePrice), 4) AS avg_price_variance
FROM purchases p
JOIN purchase_prices pp
  ON p.VendorNumber = pp.VendorNumber
 AND p.Brand = pp.Brand
 AND p.Size = pp.Size
GROUP BY p.VendorNumber, p.VendorName, p.Brand, p.Description, p.Size
ORDER BY avg_price_variance DESC;
"""
pd.read_sql(q, conn).head(10)

,VendorNumber,VendorName,Brand,Description,Size,avg_actual_price,avg_standard_price,avg_price_variance
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,Ch Lilian 09 Ladouys St Este,750mL,23.86,23.86,0.0
1,60,ADAMBA IMPORTS INTL INC,771,Bak's Krupnik Honey Liqueur,750mL,11.44,11.44,0.0
2,105,ALTAMAR BRANDS LLC,2529,Right Gin,750mL,23.25,23.25,0.0
3,105,ALTAMAR BRANDS LLC,8412,Tequila Ocho Plata Fresno,750mL,35.71,35.71,0.0
4,200,AMERICAN SPIRITS EXCHANGE,19715,Slices Sangria Red,750mL,7.53,7.53,0.0
5,200,AMERICAN SPIRITS EXCHANGE,20789,Zin-phomaniac Znfdl,750mL,9.73,9.73,0.0
6,287,APPOLO VINEYARDS LLC,24921,Appolo Vyds Seyval,750mL,10.40,10.40,0.0
7,287,APPOLO VINEYARDS LLC,24922,Appolo Vyds China Girl,750mL,10.47,10.47,0.0
8,388,ATLANTIC IMPORTING COMPANY,2034,Glendalough Double Barrel,750mL,21.32,21.32,0.0
9,388,ATLANTIC IMPORTING COMPANY,2119,Glendalough 13 Yr Sngle Malt,750mL,66.40,66.40,0.0

* summary

In [16]:
q = """
WITH base AS (
  SELECT
    VendorNumber,
    VendorName,
    SUM(Quantity) AS total_Quantity,
    SUM(Dollars + COALESCE(Freight,0)) AS total_spend,
    ROUND((SUM(Dollars + COALESCE(Freight,0))) / NULLIF(SUM(Quantity),0), 4) AS unit_cost,
    ROUND(AVG(julianday(PayDate) - julianday(InvoiceDate)), 2) AS avg_pay_days
  FROM vendor_invoice
  WHERE InvoiceDate IS NOT NULL
  GROUP BY VendorNumber, VendorName
)
SELECT *
FROM base
ORDER BY total_spend DESC;
"""
vendor_scorecard = pd.read_sql(q, conn)
vendor_scorecard.head(10)

,VendorNumber,VendorName,total_Quantity,total_spend,unit_cost,avg_pay_days
0,3960,DIAGEO NORTH AMERICA INC,5459788,51216828.92,9.3807,35.62
1,4425,MARTIGNETTI COMPANIES,2637275,27966193.83,10.6042,36.78
2,12546,JIM BEAM BRANDS COMPANY,2737165,24327032.02,8.8877,35.67
3,17035,PERNOD RICARD USA,1647558,24247871.78,14.7175,36.07
4,480,BACARDI USA INC,1427075,17713664.99,12.4126,34.78
5,1392,CONSTELLATION BRANDS INC,2325892,15653446.89,6.7301,36.29
6,1128,BROWN-FORMAN CORP,1006122,13598034.76,13.5153,36.16
7,9165,ULTRA BEVERAGE COMPANY LLP,1077527,13278668.63,12.3233,35.69
8,3252,E & J GALLO WINERY,1858260,12351575.00,6.6468,36.55
9,9552,M S WALKER INC,1372841,10991369.12,8.0063,35.60

* Vendor-wise Profit Query

In [17]:
q = """
SELECT
    p.VendorNumber,
    p.VendorName,
    ROUND(AVG(pp.Price), 2) AS avg_selling_price,
    ROUND(AVG(p.PurchasePrice), 2) AS avg_actual_cost,
    
    ROUND(AVG(pp.Price - p.PurchasePrice), 2) AS profit_per_unit,
    
    SUM(p.Quantity) AS total_Quantity,
    
    ROUND(SUM((pp.Price - p.PurchasePrice) * p.Quantity), 2) AS total_profit,
    
    ROUND(AVG((pp.Price - p.PurchasePrice) / pp.Price) * 100, 2) AS margin_percent

FROM purchases p
JOIN purchase_prices pp
  ON p.VendorNumber = pp.VendorNumber
 AND p.Brand = pp.Brand
 AND p.Size = pp.Size

GROUP BY p.VendorNumber, p.VendorName
ORDER BY total_profit DESC;
"""

pd.read_sql(q, conn).head(10)

,VendorNumber,VendorName,avg_selling_price,avg_actual_cost,profit_per_unit,total_Quantity,total_profit,margin_percent
0,4425,MARTIGNETTI COMPANIES,17.61,11.36,6.25,2106354,11842304.68,35.47
1,3960,DIAGEO NORTH AMERICA INC,18.58,13.57,5.01,3938905,8559983.29,26.91
2,1392,CONSTELLATION BRANDS INC,10.75,6.53,4.22,1468395,6013153.82,38.98
3,9165,ULTRA BEVERAGE COMPANY LLP,23.66,16.18,7.48,942149,5832947.02,33.64
4,3252,E & J GALLO WINERY,10.37,6.48,3.89,1416901,5384614.71,37.99
5,12546,JIM BEAM BRANDS COMPANY,16.20,11.78,4.42,1893177,4748908.97,27.35
6,17035,PERNOD RICARD USA,23.14,16.64,6.50,1011997,4409177.02,28.85
7,9552,M S WALKER INC,13.93,9.08,4.85,956493,4247584.91,35.08
8,8112,MOET HENNESSY USA INC,39.43,27.06,12.38,376244,3610927.77,31.23
9,480,BACARDI USA INC,16.42,11.44,4.98,862628,3307569.42,31.72

* Check how much risk which vendor

In [18]:
q = """
WITH profit AS (
  SELECT
    p.VendorNumber,
    ROUND(
      AVG((pp.Price - p.PurchasePrice) / NULLIF(pp.Price,0)) * 100,
      2
    ) AS margin_percent
  FROM purchases p
  JOIN purchase_prices pp
    ON p.VendorNumber = pp.VendorNumber
   AND p.Brand = pp.Brand
   AND (
        TRIM(p.Size) = TRIM(pp.Size)
        OR (
            LOWER(pp.Size) LIKE '%ml'
            AND TRIM(p.Size) =
              ROUND(CAST(REPLACE(LOWER(pp.Size),'ml','') AS REAL)/1000.0, 2) || 'L'
        )
   )
  WHERE pp.Price IS NOT NULL AND pp.Price > 0
  GROUP BY p.VendorNumber
),

base AS (
  SELECT
    VendorNumber,
    VendorName,
    SUM(Quantity) AS total_Quantity,
    SUM(Dollars + COALESCE(Freight,0)) AS total_spend,
    ROUND(
      (SUM(Dollars + COALESCE(Freight,0)) / NULLIF(SUM(Quantity),0)),
      4
    ) AS unit_cost_incl_freight,
    ROUND(
      AVG(julianday(PayDate) - julianday(InvoiceDate)),
      2
    ) AS avg_payment_days
  FROM vendor_invoice
  WHERE InvoiceDate IS NOT NULL
    AND PayDate IS NOT NULL
    AND julianday(PayDate) >= julianday(InvoiceDate)
  GROUP BY VendorNumber, VendorName
),

purchase_totals AS (
  SELECT
    VendorNumber,
    SUM(Quantity) AS TotalPurchaseQuantity,
    SUM(Dollars)  AS TotalPurchaseDollars,
    ROUND(AVG(PurchasePrice), 4) AS PurchasePrice
  FROM purchases
  GROUP BY VendorNumber
),

actual_price AS (
  SELECT
    VendorNumber,
    ROUND(AVG(Price), 4) AS ActualPrice,
    ROUND(AVG(Volume), 2) AS Volume
  FROM purchase_prices
  WHERE Price IS NOT NULL AND Price > 0
  GROUP BY VendorNumber
),

sales_totals AS (
  SELECT
    VendorNo AS VendorNumber,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(SalesDollars)  AS TotalSalesDollars,
    ROUND(
      (SUM(SalesDollars) / NULLIF(SUM(SalesQuantity),0)),
      4
    ) AS TotalSalesPrice,
    ROUND(SUM(ExciseTax), 2) AS TotalExciseTax
  FROM sales
  GROUP BY VendorNo
),

freight_totals AS (
  SELECT
    VendorNumber,
    ROUND(SUM(COALESCE(Freight,0)), 2) AS FreightCost
  FROM vendor_invoice
  GROUP BY VendorNumber
),

ranked AS (
  SELECT
    b.*,
    p.margin_percent,
    PERCENT_RANK() OVER (ORDER BY total_spend DESC)            AS spend_risk,
    PERCENT_RANK() OVER (ORDER BY unit_cost_incl_freight DESC) AS unit_cost_risk,
    PERCENT_RANK() OVER (ORDER BY avg_payment_days DESC)       AS payment_risk
  FROM base b
  LEFT JOIN profit p
    ON b.VendorNumber = p.VendorNumber
)

SELECT
  r.VendorNumber,
  r.VendorName,

  pt.PurchasePrice,
  ap.ActualPrice,
  ap.Volume,
  pt.TotalPurchaseQuantity,
  pt.TotalPurchaseDollars,
  st.TotalSalesQuantity,
  st.TotalSalesDollars,
  st.TotalSalesPrice,
  st.TotalExciseTax,
  ft.FreightCost,

  r.total_Quantity,
  r.total_spend,
  r.unit_cost_incl_freight,
  r.avg_payment_days,
  r.margin_percent,
  ROUND((r.spend_risk + r.unit_cost_risk + r.payment_risk)/3.0, 3) AS risk_score,
  CASE
    WHEN ((r.spend_risk + r.unit_cost_risk + r.payment_risk)/3.0) >= 0.67 THEN 'HIGH'
    WHEN ((r.spend_risk + r.unit_cost_risk + r.payment_risk)/3.0) >= 0.34 THEN 'MEDIUM'
    ELSE 'LOW'
  END AS risk_band
FROM ranked r
LEFT JOIN purchase_totals pt
  ON r.VendorNumber = pt.VendorNumber
LEFT JOIN actual_price ap
  ON r.VendorNumber = ap.VendorNumber
LEFT JOIN sales_totals st
  ON r.VendorNumber = st.VendorNumber
LEFT JOIN freight_totals ft
  ON r.VendorNumber = ft.VendorNumber
ORDER BY risk_score DESC, r.total_spend DESC;
"""

vendor_scorecard = pd.read_sql(q, conn)
vendor_scorecard.head(10)

,VendorNumber,VendorName,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,total_Quantity,total_spend,unit_cost_incl_freight,avg_payment_days,margin_percent,risk_score,risk_band
0,90026,SILVER MOUNTAIN CIDERS,4.5400,11.3900,730.00,17,77.18,52.0,381.48,7.3362,5.17,0.36,17,77.54,4.5612,30.50,NaN,0.987,HIGH
1,90033,FANTASY FINE WINES CORP,5.3600,7.9900,750.00,24,128.64,41.0,327.59,7.9900,4.51,0.61,24,129.25,5.3854,29.00,32.92,0.974,HIGH
2,2396,BLACK PRINCE DISTILLERY INC,7.4547,7.3900,1275.00,807,5971.94,1115.0,11818.85,10.5999,986.13,30.98,807,6002.92,7.4386,33.34,36.15,0.859,HIGH
3,90052,HAUNTING WHISPER VYDS,8.0698,11.9900,750.00,669,5388.58,611.0,7325.89,11.9900,67.62,27.61,669,5416.19,8.0959,33.10,32.70,0.854,HIGH
4,90017,THE IMPORTED GRAPE LLC,7.2305,18.6775,743.75,2280,16093.77,1736.0,22179.74,12.7763,194.00,80.03,2280,16173.80,7.0938,34.40,43.90,0.836,HIGH
5,5083,LOYAL DOG WINERY,9.6700,14.9900,750.00,240,2320.80,74.0,1111.26,15.0170,8.18,10.68,240,2331.48,9.7145,28.67,35.49,0.831,HIGH
6,9099,TRUETT HURST,9.8600,14.9900,750.00,24,236.64,1.0,14.99,14.9900,0.11,1.25,24,237.89,9.9121,31.00,34.22,0.823,HIGH
7,8920,TAKARA SAKE USA INC,7.1948,32.0233,6350.00,9066,45289.34,8973.0,64082.97,7.1418,5327.70,232.99,9066,45522.33,5.0212,34.67,28.99,0.799,HIGH
8,1439,CAPSTONE INTERNATIONAL,13.6600,25.9900,1250.00,4,54.64,13.0,246.87,18.9900,23.89,0.27,4,54.91,13.7275,31.00,49.39,0.753,HIGH
9,90027,POVERTY LANE ORCHARDS,7.7135,12.0525,750.00,5872,45269.01,6341.0,73642.09,11.6136,704.22,229.88,5872,45498.89,7.7484,34.57,33.60,0.747,HIGH

In [19]:
vendor_scorecard.dtypes

VendorNumber                int64
VendorName                 object
PurchasePrice             float64
ActualPrice               float64
Volume                    float64
TotalPurchaseQuantity       int64
TotalPurchaseDollars      float64
TotalSalesQuantity        float64
TotalSalesDollars         float64
TotalSalesPrice           float64
TotalExciseTax            float64
FreightCost               float64
total_Quantity              int64
total_spend               float64
unit_cost_incl_freight    float64
avg_payment_days          float64
margin_percent            float64
risk_score                float64
risk_band                  object
dtype: object

In [20]:
vendor_scorecard.isnull().sum()

VendorNumber              0
VendorName                0
PurchasePrice             0
ActualPrice               1
Volume                    1
TotalPurchaseQuantity     0
TotalPurchaseDollars      0
TotalSalesQuantity        2
TotalSalesDollars         2
TotalSalesPrice           2
TotalExciseTax            2
FreightCost               0
total_Quantity            0
total_spend               0
unit_cost_incl_freight    0
avg_payment_days          0
margin_percent            3
risk_score                0
risk_band                 0
dtype: int64

In [21]:
vendor_scorecard['VendorName'].unique()

array(['SILVER MOUNTAIN CIDERS     ', 'FANTASY FINE WINES CORP    ',
       'BLACK PRINCE DISTILLERY INC', 'HAUNTING WHISPER VYDS      ',
       'THE IMPORTED GRAPE LLC     ', 'LOYAL DOG WINERY           ',
       'TRUETT HURST               ', 'TAKARA SAKE USA INC        ',
       'CAPSTONE INTERNATIONAL     ', 'POVERTY LANE ORCHARDS      ',
       'OLE SMOKY DISTILLERY LLC   ', 'CENTEUR IMPORTS LLC        ',
       'BRONCO WINE COMPANY        ', 'THE PIERPONT GROUP LLC     ',
       'FULCHINO VINEYARD INC      ', 'ZORVINO VINEYARDS          ',
       'LATITUDE BEVERAGE COMPANY  ', 'PSP WINES ',
       'TRINCHERO FAMILY ESTATES   ', 'SURVILLE ENTERPRISES CORP  ',
       'CHARLES JACQUIN ET CIE INC ', 'INCREDIBREW INC            ',
       'MOONLIGHT MEADERY          ', 'MILTONS DISTRIBUTING CO    ',
       'LAUREATE IMPORTS CO        ', 'DUGGANS DISTILLED PRODUCTS ',
       'AMERICAN SPIRITS EXCHANGE  ', 'TREASURY WINE ESTATES      ',
       'TY KU LLC                  ', 'WALPOLE MTN VIEW WINERY    ',
       'WESTERN SPIRITS BEVERAGE CO', 'PINE STATE TRADING CO      ',
       'STE MICHELLE WINE ESTATES  ', 'VINEYARD BRANDS LLC        ',
       'PREMIUM PORT WINES, INC.   ', 'LUXCO INC                  ',
       'SHAW ROSS INT L IMP LTD    ', 'SEA BREEZE CELLARS LLC     ',
       'STELLAR IMPORTING CO LLC   ', 'MCCORMICK DISTILLING CO    ',
       'BANFI PRODUCTS CORP        ', 'VINEYARD BRANDS INC        ',
       'SOUTHERN GLAZERS W&S OF NE ', 'SWEET BABY VINEYARD        ',
       'VINEXTRA INC               ', 'JEWELL TOWNE VINEYARDS     ',
       'CANDIA VINEYARDS           ', 'STAR INDUSTRIES INC.       ',
       'MHW LTD                    ', 'TAMWORTH DISTILLING        ',
       'MANGO BOTTLING INC         ', 'DIAGEO CHATEAU ESTATE WINES',
       'KLIN SPIRITS LLC           ', 'SWEETWATER FARM         ',
       'HOOD RIVER DISTILLERS, Inc.', 'FLAG HILL WINERY & VINEYARD',
       'CRUSH WINES                ', 'FORTUNE WINE BROKERS LLC   ',
       'ALTAMAR BRANDS LLC         ', 'NICHE W & S                ',
       'APPOLO VINEYARDS LLC       ', 'WINE GROUP INC             ',
       'HEAVEN HILL DISTILLERIES   ', 'STOLI GROUP,(USA) LLC      ',
       'BULLY BOY DISTILLERS       ', 'VINILANDIA USA             ',
       'TALL SHIP DISTILLERY LLC   ', 'ATLANTIC IMPORTING COMPANY ',
       'GILMANTON WINERY & VINEYARD', 'KOBRAND CORPORATION        ',
       'AMERICAN VINTAGE BEVERAGE  ', 'SAZERAC CO INC             ',
       'WEIN BAUER INC             ', 'PHILLIPS PRODUCTS CO.      ',
       'PALM BAY INTERNATIONAL INC ', 'BLACK ROCK SPIRITS LLC     ',
       'SAZERAC NORTH AMERICA INC. ', 'SMOKY QUARTZ DISTILLERY LLC',
       'M S WALKER INC             ', 'STARK BREWING COMPANY      ',
       'PERFECTA WINES             ', 'STATE WINE & SPIRITS   ',
       'UNCORKED       ', 'FABRIZIA SPIRITS LLC       ',
       'IRA GOLDMAN AND WILLIAMS, LLP          ',
       'LABELLE VYDS AND WINERY    ', 'FLAVOR ESSENCE INC         ',
       'DELICATO VINEYARDS INC     ', 'CONSTELLATION BRANDS INC   ',
       'HIGHLAND WINE MERCHANTS LLC', 'LAIRD & CO                 ',
       'BACARDI USA INC            ', 'FREDERICK WILDMAN & SONS   ',
       'ADAMBA IMPORTS INTL INC    ', 'Russian Standard Vodka     ',
       'E & J GALLO WINERY         ', 'CAMPARI AMERICA            ',
       'BLACK COVE BEVERAGES       ', 'JIM BEAM BRANDS COMPANY    ',
       'Circa Wines                ', 'SIDNEY FRANK IMPORTING CO  ',
       'MARTIGNETTI COMPANIES ', 'DIAGEO NORTH AMERICA INC   ',
       'PROXIMO SPIRITS INC.       ', 'MAJESTIC FINE WINES        ',
       'CALEDONIA SPIRITS INC      ', 'SEA HAGG DISTILLERY LLC    ',
       'Dunn Wine Brokers          ', 'DJINN SPIRITS LLC          ',
       'VRANKEN AMERICA            ', 'PARK STREET IMPORTS LLC    ',
       'VINEDREA WINES LLC         ', 'AAPER ALCOHOL & CHEMICAL CO',
       'SOUTHERN WINE & SPIRITS NE ', 'PREMIER DISTRIBUTORS       ',
       'DISARONNO INTERNATIONAL LLC', 'EDRINGTON AMERICAS         ',
       'CASTLE BRANDS CORP.        ', 'Serralles Usa LLC          ',
       'R.P.IMPORTS INC            ', 'ULTRA BEVERAGE COMPANY LLP ',
       'MARSALLE COMPANY           ', 'ALISA CARR BEVERAGES           ',
       'REMY COINTREAU USA INC     ', 'MOET HENNESSY USA INC      ',
       'MARTIGNETTI COMPANIES', 'BROWN-FORMAN CORP          ',
       'PERNOD RICARD USA          ', 'WILLIAM GRANT & SONS INC   '],
      dtype=object)

In [22]:
vendor_scorecard.fillna(0,inplace=True)

In [23]:
vendor_scorecard.isnull().sum()

VendorNumber              0
VendorName                0
PurchasePrice             0
ActualPrice               0
Volume                    0
TotalPurchaseQuantity     0
TotalPurchaseDollars      0
TotalSalesQuantity        0
TotalSalesDollars         0
TotalSalesPrice           0
TotalExciseTax            0
FreightCost               0
total_Quantity            0
total_spend               0
unit_cost_incl_freight    0
avg_payment_days          0
margin_percent            0
risk_score                0
risk_band                 0
dtype: int64

In [24]:
vendor_scorecard['VendorName'] = vendor_scorecard['VendorName'].str.strip()

In [25]:
vendor_scorecard['VendorName'].unique()

array(['SILVER MOUNTAIN CIDERS', 'FANTASY FINE WINES CORP',
       'BLACK PRINCE DISTILLERY INC', 'HAUNTING WHISPER VYDS',
       'THE IMPORTED GRAPE LLC', 'LOYAL DOG WINERY', 'TRUETT HURST',
       'TAKARA SAKE USA INC', 'CAPSTONE INTERNATIONAL',
       'POVERTY LANE ORCHARDS', 'OLE SMOKY DISTILLERY LLC',
       'CENTEUR IMPORTS LLC', 'BRONCO WINE COMPANY',
       'THE PIERPONT GROUP LLC', 'FULCHINO VINEYARD INC',
       'ZORVINO VINEYARDS', 'LATITUDE BEVERAGE COMPANY', 'PSP WINES',
       'TRINCHERO FAMILY ESTATES', 'SURVILLE ENTERPRISES CORP',
       'CHARLES JACQUIN ET CIE INC', 'INCREDIBREW INC',
       'MOONLIGHT MEADERY', 'MILTONS DISTRIBUTING CO',
       'LAUREATE IMPORTS CO', 'DUGGANS DISTILLED PRODUCTS',
       'AMERICAN SPIRITS EXCHANGE', 'TREASURY WINE ESTATES', 'TY KU LLC',
       'WALPOLE MTN VIEW WINERY', 'WESTERN SPIRITS BEVERAGE CO',
       'PINE STATE TRADING CO', 'STE MICHELLE WINE ESTATES',
       'VINEYARD BRANDS LLC', 'PREMIUM PORT WINES, INC.', 'LUXCO INC',
       'SHAW ROSS INT L IMP LTD', 'SEA BREEZE CELLARS LLC',
       'STELLAR IMPORTING CO LLC', 'MCCORMICK DISTILLING CO',
       'BANFI PRODUCTS CORP', 'VINEYARD BRANDS INC',
       'SOUTHERN GLAZERS W&S OF NE', 'SWEET BABY VINEYARD',
       'VINEXTRA INC', 'JEWELL TOWNE VINEYARDS', 'CANDIA VINEYARDS',
       'STAR INDUSTRIES INC.', 'MHW LTD', 'TAMWORTH DISTILLING',
       'MANGO BOTTLING INC', 'DIAGEO CHATEAU ESTATE WINES',
       'KLIN SPIRITS LLC', 'SWEETWATER FARM',
       'HOOD RIVER DISTILLERS, Inc.', 'FLAG HILL WINERY & VINEYARD',
       'CRUSH WINES', 'FORTUNE WINE BROKERS LLC', 'ALTAMAR BRANDS LLC',
       'NICHE W & S', 'APPOLO VINEYARDS LLC', 'WINE GROUP INC',
       'HEAVEN HILL DISTILLERIES', 'STOLI GROUP,(USA) LLC',
       'BULLY BOY DISTILLERS', 'VINILANDIA USA',
       'TALL SHIP DISTILLERY LLC', 'ATLANTIC IMPORTING COMPANY',
       'GILMANTON WINERY & VINEYARD', 'KOBRAND CORPORATION',
       'AMERICAN VINTAGE BEVERAGE', 'SAZERAC CO INC', 'WEIN BAUER INC',
       'PHILLIPS PRODUCTS CO.', 'PALM BAY INTERNATIONAL INC',
       'BLACK ROCK SPIRITS LLC', 'SAZERAC NORTH AMERICA INC.',
       'SMOKY QUARTZ DISTILLERY LLC', 'M S WALKER INC',
       'STARK BREWING COMPANY', 'PERFECTA WINES', 'STATE WINE & SPIRITS',
       'UNCORKED', 'FABRIZIA SPIRITS LLC',
       'IRA GOLDMAN AND WILLIAMS, LLP', 'LABELLE VYDS AND WINERY',
       'FLAVOR ESSENCE INC', 'DELICATO VINEYARDS INC',
       'CONSTELLATION BRANDS INC', 'HIGHLAND WINE MERCHANTS LLC',
       'LAIRD & CO', 'BACARDI USA INC', 'FREDERICK WILDMAN & SONS',
       'ADAMBA IMPORTS INTL INC', 'Russian Standard Vodka',
       'E & J GALLO WINERY', 'CAMPARI AMERICA', 'BLACK COVE BEVERAGES',
       'JIM BEAM BRANDS COMPANY', 'Circa Wines',
       'SIDNEY FRANK IMPORTING CO', 'MARTIGNETTI COMPANIES',
       'DIAGEO NORTH AMERICA INC', 'PROXIMO SPIRITS INC.',
       'MAJESTIC FINE WINES', 'CALEDONIA SPIRITS INC',
       'SEA HAGG DISTILLERY LLC', 'Dunn Wine Brokers',
       'DJINN SPIRITS LLC', 'VRANKEN AMERICA', 'PARK STREET IMPORTS LLC',
       'VINEDREA WINES LLC', 'AAPER ALCOHOL & CHEMICAL CO',
       'SOUTHERN WINE & SPIRITS NE', 'PREMIER DISTRIBUTORS',
       'DISARONNO INTERNATIONAL LLC', 'EDRINGTON AMERICAS',
       'CASTLE BRANDS CORP.', 'Serralles Usa LLC', 'R.P.IMPORTS INC',
       'ULTRA BEVERAGE COMPANY LLP', 'MARSALLE COMPANY',
       'ALISA CARR BEVERAGES', 'REMY COINTREAU USA INC',
       'MOET HENNESSY USA INC', 'BROWN-FORMAN CORP', 'PERNOD RICARD USA',
       'WILLIAM GRANT & SONS INC'], dtype=object)

In [26]:
# Gross Profit
vendor_scorecard["GrossProfit"] = (
    vendor_scorecard["TotalSalesDollars"] - 
    vendor_scorecard["TotalPurchaseDollars"]
)

In [27]:
# Profit Margin (%)
vendor_scorecard["ProfitMargin"] = (
    vendor_scorecard["GrossProfit"] / 
    vendor_scorecard["TotalSalesDollars"]
) * 100

In [28]:
vendor_scorecard["StockTurnover"] = (
   vendor_scorecard["TotalSalesQuantity"] / 
   vendor_scorecard["TotalPurchaseQuantity"]
)

In [29]:
# Sales to Purchase Ratio
vendor_scorecard["SalestoPurchaseRatio"] = (
    vendor_scorecard["TotalSalesDollars"] / 
    vendor_scorecard["TotalPurchaseDollars"]
)

In [30]:
vendor_scorecard.columns

Index(['VendorNumber', 'VendorName', 'PurchasePrice', 'ActualPrice', 'Volume',
       'TotalPurchaseQuantity', 'TotalPurchaseDollars', 'TotalSalesQuantity',
       'TotalSalesDollars', 'TotalSalesPrice', 'TotalExciseTax', 'FreightCost',
       'total_Quantity', 'total_spend', 'unit_cost_incl_freight',
       'avg_payment_days', 'margin_percent', 'risk_score', 'risk_band',
       'GrossProfit', 'ProfitMargin', 'StockTurnover', 'SalestoPurchaseRatio'],
      dtype='object')

In [31]:
vendor_scorecard.dtypes

VendorNumber                int64
VendorName                 object
PurchasePrice             float64
ActualPrice               float64
Volume                    float64
TotalPurchaseQuantity       int64
TotalPurchaseDollars      float64
TotalSalesQuantity        float64
TotalSalesDollars         float64
TotalSalesPrice           float64
TotalExciseTax            float64
FreightCost               float64
total_Quantity              int64
total_spend               float64
unit_cost_incl_freight    float64
avg_payment_days          float64
margin_percent            float64
risk_score                float64
risk_band                  object
GrossProfit               float64
ProfitMargin              float64
StockTurnover             float64
SalestoPurchaseRatio      float64
dtype: object

In [32]:
vendor_scorecard.head(10)

,VendorNumber,VendorName,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,total_Quantity,total_spend,unit_cost_incl_freight,avg_payment_days,margin_percent,risk_score,risk_band,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,90026,SILVER MOUNTAIN CIDERS,4.5400,11.3900,730.00,17,77.18,52.0,381.48,7.3362,5.17,0.36,17,77.54,4.5612,30.50,0.00,0.987,HIGH,304.30,79.768271,3.058824,4.942731
1,90033,FANTASY FINE WINES CORP,5.3600,7.9900,750.00,24,128.64,41.0,327.59,7.9900,4.51,0.61,24,129.25,5.3854,29.00,32.92,0.974,HIGH,198.95,60.731402,1.708333,2.546564
2,2396,BLACK PRINCE DISTILLERY INC,7.4547,7.3900,1275.00,807,5971.94,1115.0,11818.85,10.5999,986.13,30.98,807,6002.92,7.4386,33.34,36.15,0.859,HIGH,5846.91,49.471057,1.381660,1.979064
3,90052,HAUNTING WHISPER VYDS,8.0698,11.9900,750.00,669,5388.58,611.0,7325.89,11.9900,67.62,27.61,669,5416.19,8.0959,33.10,32.70,0.854,HIGH,1937.31,26.444705,0.913303,1.359521
4,90017,THE IMPORTED GRAPE LLC,7.2305,18.6775,743.75,2280,16093.77,1736.0,22179.74,12.7763,194.00,80.03,2280,16173.80,7.0938,34.40,43.90,0.836,HIGH,6085.97,27.439321,0.761404,1.378157
5,5083,LOYAL DOG WINERY,9.6700,14.9900,750.00,240,2320.80,74.0,1111.26,15.0170,8.18,10.68,240,2331.48,9.7145,28.67,35.49,0.831,HIGH,-1209.54,-108.844015,0.308333,0.478826
6,9099,TRUETT HURST,9.8600,14.9900,750.00,24,236.64,1.0,14.99,14.9900,0.11,1.25,24,237.89,9.9121,31.00,34.22,0.823,HIGH,-221.65,-1478.652435,0.041667,0.063345
7,8920,TAKARA SAKE USA INC,7.1948,32.0233,6350.00,9066,45289.34,8973.0,64082.97,7.1418,5327.70,232.99,9066,45522.33,5.0212,34.67,28.99,0.799,HIGH,18793.63,29.327027,0.989742,1.414968
8,1439,CAPSTONE INTERNATIONAL,13.6600,25.9900,1250.00,4,54.64,13.0,246.87,18.9900,23.89,0.27,4,54.91,13.7275,31.00,49.39,0.753,HIGH,192.23,77.866894,3.250000,4.518119
9,90027,POVERTY LANE ORCHARDS,7.7135,12.0525,750.00,5872,45269.01,6341.0,73642.09,11.6136,704.22,229.88,5872,45498.89,7.7484,34.57,33.60,0.747,HIGH,28373.08,38.528347,1.079871,1.626766

In [33]:
vendor_scorecard.to_sql(
    "vendor_scorecard_final",
    conn,
    if_exists="replace",
    index=False
)

129

In [34]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)

                     name
0         begin_inventory
1           end_inventory
2               purchases
3         purchase_prices
4                   sales
5          vendor_invoice
6    vendor_final_summary
7  vendor_scorecard_final

In [35]:
pd.read_sql("SELECT * FROM vendor_scorecard_final LIMIT 5", conn)

,VendorNumber,VendorName,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,total_Quantity,total_spend,unit_cost_incl_freight,avg_payment_days,margin_percent,risk_score,risk_band,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,90026,SILVER MOUNTAIN CIDERS,4.5400,11.3900,730.00,17,77.18,52.0,381.48,7.3362,5.17,0.36,17,77.54,4.5612,30.50,0.00,0.987,HIGH,304.30,79.768271,3.058824,4.942731
1,90033,FANTASY FINE WINES CORP,5.3600,7.9900,750.00,24,128.64,41.0,327.59,7.9900,4.51,0.61,24,129.25,5.3854,29.00,32.92,0.974,HIGH,198.95,60.731402,1.708333,2.546564
2,2396,BLACK PRINCE DISTILLERY INC,7.4547,7.3900,1275.00,807,5971.94,1115.0,11818.85,10.5999,986.13,30.98,807,6002.92,7.4386,33.34,36.15,0.859,HIGH,5846.91,49.471057,1.381660,1.979064
3,90052,HAUNTING WHISPER VYDS,8.0698,11.9900,750.00,669,5388.58,611.0,7325.89,11.9900,67.62,27.61,669,5416.19,8.0959,33.10,32.70,0.854,HIGH,1937.31,26.444705,0.913303,1.359521
4,90017,THE IMPORTED GRAPE LLC,7.2305,18.6775,743.75,2280,16093.77,1736.0,22179.74,12.7763,194.00,80.03,2280,16173.80,7.0938,34.40,43.90,0.836,HIGH,6085.97,27.439321,0.761404,1.378157

In [38]:
vendor_scorecard.to_csv(
    "vendor_scorecard_final.csv",
    index=False
)